.github/workflows/test.yml, tests/pytest.ini, tests/test_device.py, tests/test_qasm.py
Setting up basic CI for Python 3.6 and Python 3.9 on Windows, Mac and Linux.
I'm a bit surprised that the test on Windows works without any special tuning for VS and Cython. Maybe it is because `qutip_qip` does not use run-time compiling.
Never worked on GitHub Action before, suggestions are welcome.
=> Add github action for test

src/qutip_qip/device/processor.py, tests/test_processor.py
Allow one to modify `tlist` in the `Processor` to prevent saving all intermediate states, see https://github.com/qutip/qutip/issues/1472.
=> Remove the restriction on tlist in processor

docs/source/qip-processor.rst, src/qutip_qip/compiler/cavityqedcompiler.py, src/qutip_qip/compiler/gatecompiler.py, src/qutip_qip/compiler/spinchaincompiler.py, src/qutip_qip/device/cavityqed.py, src/qutip_qip/device/modelprocessor.py, src/qutip_qip/device/processor.py, src/qutip_qip/device/spinchain.py, tests/test_compiler.py, tests/test_processor.py
- Use num_qubits instead of N, the latter is still provided as a keyword argument for compatibility.
- The compiler now returns a dictionary between the pulse label and compiled coeffs. The processor is able to handle this directly.
There is no need to pass a pulse_dict variable.
- `load_circuit` is defined in `ModelProcessor`, so that the customized processor no longer needs to provide this.
=> Simplify the interface of compiler

tests/test_pulse.py
The tests in `test_pulse` were not run when tested with `pytest test_pulse.py`. 
The new changes make sure pytest runs the tests instead of skipping them.
=> Make test_pulse consistent with pytest

docs/source/qip-basics.rst
The H gate is named SNOT in the current version. Correct the docs. #32 
We cannot really test circuit plotting because it requires latex and lots of others software to work.
At some point, we should support both names. This will be much easier after the refactor of the gate representation. @purva-thakre I think it won't be much work once the gate classes are built, right? We can have `H` as a subclass of `SNOT` or vice versa.
=> Fix the wrong gate name in the doc

tests/test_device.py
SCQubits have a lower fidelity because of leakage.
The previous test may fail with about a probability of 10~20%.
=> Loose the tests accuracy a bit for numerical circuit tests

README.md, docs/source/installation.rst, src/qutip_qip/device/cavityqed.py, src/qutip_qip/device/circuitqed.py
Fix inconsistency in the docstrings of some processors. The default value is defined in the `__init__` method of the class.
Correct the guide for using `doctest`, fix #38
=> Correct some docs

README.md, docs/source/installation.rst, src/qutip_qip/__init__.py
I realized that since this is the first release, I also need to update the README with the installation guide for `pip` install. This README will be shown on the PyPI website after the release just like this one with TestPyPI https://test.pypi.org/project/qutip-qip/.
The doc is not packed with the package so it doesn't really matter, but sooner or later I will need to do this anyway.
Please confirm if this is correct. @nathanshammah @quantshah @jakelishman @hodgestar
=> Prepare release v0.1.0 step 2

README.md, doc/source/index.rst, doc/source/introduction.rst, doc/source/tutorials.rst
As discussed in #33, links to tutorials are added in documentation and `readme.md`. 
For the moment, haven't changed the anchor as requested in above issue since Boxi had a PR for it.
=> Links tutorials

README.md, doc/source/contribution-code.rst
Adds some information about running local tests, generating local code coverage and making sure [new code is PEP8 compliant](https://github.com/qutip/qutip-qip/pull/53#issuecomment-860247855). 
Wanted to add generating local code coverage because this helps avoid pushing to github every time there's a need to check for code coverage.
=> Update contribution guidelines

src/qutip_qip/circuit_latex.py
This file included GPL'd code, which is incompatible with QuTiP's 3-clause BSD licence.  Instead, we rely on the user to have a functional install of the file (it's been included in TeXLive since at least 2014).
This also attempts to maintain patches made to the LaTeX code.
See qutip/qutip#1579
This is the same PR as qutip/qutip#1580, effectively.
=> Remove vendored qcircuit.tex

src/qutip_qip/device/processor.py, tests/test_processor.py
**Description**
In the analytical calculation of the circuit unitaries in `Processor`, the drift Hamiltonian was missing. Add it and add a test accordingly. Also fix a wrong docstring.
Equivalent to https://github.com/qutip/qutip/pull/1603
**Related issues or PRs**
fix https://github.com/qutip/qutip/issues/1602
**Changelog**
Add the missing drift Hamiltonian to the method `run_analytically` of `Processor`
=> Add the missing drift Hamiltonian to the method `run_analytically` of `Processor`

src/qutip_qip/noise.py, tests/test_noise.py
**Description**
In the noise module, users are allowed to define custom noise for their own physical model. The `Noise` class uses a hook method `get_noisy_dynamics` to realize this. This method will be called when including noise in the physical model.
It was pointed out by @quantshah that the name `get_noisy_dynamics` was wrong because the noise object returns a list of `Pulse`, instead of `QobjEvo`. This PR fixed this issue and use the term `get_noisy_pulses`. The old API is still usable but will issue a `PendingDeprecationWarning`.
I also copied the docstring of `get_noisy_pulses` to those in the subclass for easier reference. I originally thought that if the docstrings are missing, they will be inherited automatically, but this is not the case.
I also pinned @hodgestar because I …
=> Rename get_noisy_dynamics to get_noisy_pulses

src/qutip_qip/noise.py, tests/test_processor.py
A list of noise objects defined by the user is passed to the function. However, when adding T1 and T2 noise, the generated objects were added directly to the list. This changes the `noise_list` defined by the user and is a problem if the same `Processor` instance is used to perform more than one simulation. The T1,T2 noise objects from the previous run will accumulate in the `noise_list`. Therefore, we copy the list before add T1 T2 noise.
=> Fix the leaking noise objects

doc/source/qip-basics.rst, src/qutip_qip/circuit.py, src/qutip_qip/operations/gates.py, tests/test_circuit.py
**Changes**
- Merge the duplicated `QubitCircuit.propagators` methods.
- Move the definition for gate operators to the `Gate` class: one method defining the compact gate operator as Qobj, while the other one expands it to the full Hilbert space. This makes it easier to define subclasses for each gate later.
- Rename a previously undocumented `QubitCircuit.get_inds` method to `get_all_qubits` and add documentation. It was added recently but never documented.
There are two new method for `Gate`: `get_qobj` and `get_compact_qobj`. Although they could be merged to one, I made them two different methods because if for custom gate, I wish that the user only need to define `get_compact_qobj`, without having to consider permutation and expanding etc. And in `get_qobj`, we take care of that.
The …
=> Separate the gate definition from the QubitCircuit.propagators method

doc/source/qip-processor.rst, src/qutip_qip/compiler/cavityqedcompiler.py, src/qutip_qip/compiler/circuitqedcompiler.py, src/qutip_qip/compiler/gatecompiler.py, src/qutip_qip/compiler/spinchaincompiler.py, src/qutip_qip/device/cavityqed.py, tests/test_compiler.py
- Different pulse shapes are generated using window function from scipy.signal.windows.
- A generate_pulse_shape method is defined and can be used to generate pulse shape with the arbitrary area and required maximum.
- A default single qubit compiler is defined and simplifies the various compiler subclasses.
=> Support different pulse shapes

doc/pulse-paper/pulse_simulation.py, doc/source/apidoc/qutip_qip.device.rst, doc/source/qip-processor.rst, src/qutip_qip/device/__init__.py, src/qutip_qip/device/cavityqed.py, src/qutip_qip/device/circuitqed.py, src/qutip_qip/device/modelprocessor.py, src/qutip_qip/device/optpulseprocessor.py, src/qutip_qip/device/processor.py, src/qutip_qip/device/spinchain.py, src/qutip_qip/noise.py, tests/test_compiler.py, tests/test_device.py, tests/test_model.py, tests/test_optpulseprocessor.py, tests/test_processor.py
Previously, the Hamiltonian model in `Processor` is saved as partially initialized pulses. This PR separate the Hamiltonian model from pulse and the `Processor` class. It can now be defined independently and includes only the information of the Hamiltonian. The pulses will only be generated after the circuit is loaded.
The main changes are in `processor.py`.  In particular in the initialization. The others are either docs change or internal updates to fit this new structure. A bunch of getter functions are added to support the old way of building the Hamiltonians using the `Processor`. The data is, however, always saved in `Model`.
In principle `ModelProcessor` can be merged into `Processor`, but it is best to wait for another PR.
There are a few FIXME that are used to remind me to …
=> Separate the physical model into a Model class

src/qutip_qip/device/processor.py, tests/test_noise.py
The `get_full_tlist` method only considers the tlist in the ideal pulse. Use the tlist of the generated `QobjEvo`, which already includes all the time steps.
=> Fix a bug for the wrong tlist in c_ops

.vscode/settings.json, src/qutip_qip/compiler/scheduler.py, tests/test_scheduler.py
- Improve the readability of the scheduling algorithm.
- Add more commutation rules, such as CNOT and X on the targets, CNOT and Z on the control.
Most of the changes in the test file are just because of black styling.
@nathanshammah @quantshah
=> Improve the scheduling algorithm

src/qutip_qip/circuit.py, src/qutip_qip/circuit_latex.py, tests/test_circuit.py
- `QubitCircuit.latex_code()` now returns the full latex code (before only the code body without header), which can be saved as a tex file and compiled externally.
- The algorithm will print the latex code if pdflatex failed. This simplifies the debugging process.
@purva-thakre This should also simplify your debugging I guess?
=> Make circuit latex code accessible in QubitCircuit

src/qutip_qip/circuit.py, tests/test_circuit.py
Remove the wrong check on the initial state dimension. It assumes a qubit state. However, we also support multilevel systems such as qudits.
=> Remove the check on the initial state dimension

src/qutip_qip/circuit.py, tests/test_circuit.py
The plotting of circuits had an error for setting `reversed=False`. This was already discussed in a PR for the QuTiP repository. 
See: https://github.com/qutip/qutip/pull/1847
=> Fix Circuit Plotting for non-reversed states

tests/test_circuit.py
Separate the tests so that it skips if svg/png converters are not installed.
Use `in_temporary_directory` defined in `conftest.py` to replace the `cleanup`. Because if the test fails on the png part, the files were not cleaned.
=> Separate the png and svg tests for circuit plots

src/qutip_qip/circuit.py, tests/test_circuit.py
**Description**
The fix pertains to `add_gate` behaviour when multiple insertion indices are supplied. Prior to the proposed fix, the insertion loop doesn't take into account the fact that inserting an element in the gates list, modifies the indices in the original list, whereas the caller of `add_gate` supplies a list of indices, with positions with respect to the indices in the original list.
Additionally, the PR removes unused variables and unused function (that has also not been imported).
**Related issues or PRs**
N/A (this is the `qutip-qip` equivalent of https://github.com/qutip/qutip/issues/1497 / https://github.com/qutip/qutip/pull/1892).
**Changelog**
Fixed add_gate behavior when inserting a gate at multiple indices.
=> Fix add_gate behavior when supplied multiple indices

.github/workflows/test.yml, doc/pulse-paper/customize.py, setup.cfg, src/qutip_qip/compiler/cavityqedcompiler.py, src/qutip_qip/compiler/gatecompiler.py, src/qutip_qip/compiler/spinchaincompiler.py, src/qutip_qip/decompose/_utility.py, src/qutip_qip/device/cavityqed.py, src/qutip_qip/device/processor.py, src/qutip_qip/noise.py, src/qutip_qip/pulse.py, src/qutip_qip/vqa.py, tests/test_circuit.py, tests/test_compiler.py, tests/test_device.py, tests/test_gates.py, tests/test_measurement.py, tests/test_noise.py, tests/test_optpulseprocessor.py, tests/test_processor.py, tests/test_pulse.py
This is a replacement of #88.
- Add support of qutip=5.0 to `setup.cfg`
- New GitHub actions are added to test qutip-qip against the dev.major version of qutip
- Fix the importation errors for `qutip.Options`, use `qutip.SolverOptions` instead.
- Use `Qobj.full()` to transfer the matrix to NumPy arrays before using `assert_all_close`, since `Qobj.__array__` is removed.
- Tests are adapted for the new QobjEvo in qutip.
- Replace the `QobjEvo.ops` and `QobjEvo.cte` as they are removed. Create separate test functions to compare `QobjEvo`s.
- Remove the use of `QobjEvo.tlist`.
- Slightly modify the pulse and noise module to correctly handle the continuous/discrete pulse in `QobjEvo`.
- Fix/Improve some other unstable/wrong tests.
=> Support qutip-v5

src/qutip_qip/circuit.py, src/qutip_qip/operations/gates.py, tests/test_circuit.py
The `add_circuit` function in `QuantumCircuit` class used to copy the names of all gates without add the definition of user gates to the target circuit. Hence the user gates cannot be recognized by the new circuit. I made the copy of the definition automatic.
Same as: https://github.com/qutip/qutip/pull/1871
=> quantum circuits inherit user gates from `add_circuit`

src/qutip_qip/circuit.py, src/qutip_qip/vqa.py
The VQA module wrongly used the qutip.qip module, which is removed in qutip-v5
=> Remove qutip.qip importation

doc/pulse-paper/dj_algorithm.py, doc/source/references.bib, src/qutip_qip/compiler/circuitqedcompiler.py, src/qutip_qip/compiler/gatecompiler.py, src/qutip_qip/device/circuitqed.py, tests/test_device.py
- Add more sampling points at the beginning and the end of the idling to make sure that the pulse is zero. Prevent the effect of interpolation.
- Add a DRAG correction to the single-qubit gate of SCQubit.
=> Improve the SCQubits simulator

src/qutip_qip/circuit/circuit.py
The `arg_label` used here was undefined. `arg_label` is a member of `gate`, hence this should fix the problem.
=> Fix access on arg_label

tests/test_circuit.py, tests/test_gates.py, tests/test_optpulseprocessor.py
The signature of `rand_unitary` has changed recently in QuTiP 5. The argument `dims` no longer exists. This PR changes the two usages of `rand_unitary` by checking the version of QuTiP and then using the corresponding definition. 
The same holds for `rand_ket`.
The tests were recently failing due to this change in QuTiP 5.
=> Fix usage of `rand_unitary` and `rand_ket`

src/qutip_qip/compiler/gatecompiler.py, tests/test_compiler.py
The calculation of `final_time` was done by taking the last element of the `tlist` in `compiled_tlist`. However, the elements in `compiled_tlist` are again lists, where the first element is just a list and the second element are the actual times.
E.g. `tlist = [[0.0], np.array([...])]`
So we have to take the second ( i.e. last) element from that and then the last element to get the largest time.
The previous version sometimes produced errors when using `processor.load_circuit(...)`.
=> Final time calculation in `_concatenate_pulses`.

doc/source/qip-simulator.rst, src/qutip_qip/circuit/circuit.py, src/qutip_qip/circuit/circuitsimulator.py, tests/test_circuit.py
The parameter measure_results was not correctly processed in QubitCircuit.run because the Simulator is initialized twice. This commit removes the parameters state, cbits and measure_results from the `__init__` of CircuitSimulator and only initializes the simulator before it is run.
The CircuitSimulator class should only include information about the circuit while the information about the state is only provided when running the simulation.
Fix #164
=> Fix bug for circuit with selected measurement result

src/qutip_qip/compiler/gatecompiler.py, tests/test_compiler.py
- Fix bugs in the analytical pulse shapes
- Compress the test. The test no longer depends on the processor class. Test both the maximum and the total area.
=> Fix bugs in the analytical pulse shapes

src/qutip_qip/circuit/circuit.py
SWAP needs to be treated differently for circuits with reversed and non-reversed states order.
The fix in https://github.com/qutip/qutip-qip/pull/170 was not complete. The reason for using `\qwx[%d]` without the minus sign is actually because in `qutip-qip` the order of states is reversed.
=> SWAP gate for (non-) reversed circuit

src/qutip_qip/circuit/circuitsimulator.py, src/qutip_qip/operations/measurement.py, tests/test_measurement.py
Use the `atol` option in qutip to determine the tolerance for measurement. And filter out the states with a probability smaller than this.
See also: https://github.com/qutip/qutip/issues/2029
=> Filter the measured probability

doc/pulse-paper/qft.py, src/qutip_qip/device/processor.py, tests/test_processor.py
Similar to https://github.com/qutip/qutip/pull/2040, with a separate handling of `options` for qutip-v5.
=> Add a default max_step to the processors

.github/workflows/black.yml, .github/workflows/build.yml, .github/workflows/build_documentation.yml, .github/workflows/test.yml
- Add back the test against qutip@master (which was removed because @master was labelled as version 5.0.0 and could not be distinguished from @dev.major)
- Add a test against python 3.11
- Redistribute the test cases
- Update the versions of the GitHub built-in actions
=> Update the github actions

.github/workflows/build.yml
Use Python 3.7 for the build environment. Python 3.6 is already removed from the latest machine for Github Action.
The build was successful. https://github.com/BoxiLi/qutip-qip/actions/runs/3679944891
=> Update the build action for 0.2.X

src/qutip_qip/device/processor.py, src/qutip_qip/qiskit/backend.py, tests/test_device.py
We removed the old solvers that were existing in parallel to the new ones in qutip v5. This broke a few tests.
- Solvers options are now simple dict. The default options are per solver basis and unknown to `qutip.Options`.
- `qutip.Options` and `qutip.SolverOptions` are equivalent and deprecated.
- `mcsolve` can accept density matrix input, it use `state=` instead of `rho0=`.
- `array(qobj)` should have been not working for a while now, `full()` is the method preferred when converting to a numpy array.
- I had to reduce the `max_step` for one test... Unless there was a pulse thinner than the previous value and the solver happen to be lucky and find it previously, I don't understand why I had to reduce it that much. I hope that the idea in #184, when implemented, will be able to bring some …
=> Fix bug resulting from changing v5's default solver

.github/workflows/test.yml
We merged the branch `dev.major` branch into `master` last Monday. Thus tests against both of these branches are redundant.
I remove the test using `qutip@dev.major` since all further work for v5 will be done in `master`. It was the only test using python 3.10, so updated another test to use it.
There are no longer any active development branch for v4, all test using qutip v4 are ran using released version.
=> Remove tests again the `dev.major` branch of Qutip.

doc/source/qip-basics.rst, src/qutip_qip/operations/gateclass.py, tests/test_gates.py
=> Add QROT and MS gate

.github/workflows/test.yml
The module `qutip.control` is replaced by the package `qutip-qtrl`, see https://github.com/qutip/qutip/pull/2116.
=> Install qutip-qtrl in the test action for qutip5

.github/workflows/test.yml
- Test against the qutip alpha release.
- Install qutip-qtrl from master
=> Install qutip-qtrl master version for the tests

src/qutip_qip/device/cavityqed.py, src/qutip_qip/device/processor.py
The CavityQED processor uses discrete pulses and different gates may vary a lot in terms of the gate time. This often results in a piece of pulses being neglected by the adaptive ODE solver. Ideally, the `max_step` option should be set as half of the shortest gate time but this information is lost during the compilation and can only be estimated from the compiled pulses. This PR allows the calculation of `max_step` to be defined for each type of Processor.
This should fix the failing tests.
=> Define max_step separately for CavityQED

.github/workflows/test.yml, src/qutip_qip/device/cavityqed.py, src/qutip_qip/device/processor.py, tests/pytest.ini, tests/test_device.py, tests/test_processor.py, tests/test_vqa.py
- pytest warning to error
- Use raw string literals for docstrings with LaTeX
- Skip plotting tests correctly when matplotlib not installed
=> Cleaning a few warnings in the test

src/qutip_qip/vqa.py, tests/test_noise.py, tests/test_optpulseprocessor.py, tests/test_processor.py, tests/test_pulse.py, tests/test_qft.py, tests/test_qubits.py
It hasn't been used for a long time since we move to pytest. It is removed from `numpy.testing` now.
=> Remove run_module_suite

.github/workflows/test.yml
qutip currently limits to cython 0.29, let qutip decide which version of cython to use.
=> Do not install cython independently from qutip

src/qutip_qip/qasm.py, tests/qasm_files/w-state_with_comments.qasm, tests/test_qasm.py
QASMBench has lines that have comments after instructions, and those lines cause errors. This fix remove such comments.
=> Remove comments after meaningful statements in QASM reader

src/qutip_qip/circuit/circuit.py, tests/test_circuit.py
For circuits with a classical control and when `reverse_state=False`, the error reported in #220 occurs. This pull request changes the sign of the argument of `\ctrl` when `reverse_state=False`. With this change, the test circuit is plotted without errors:
```python
from qutip_qip.circuit import QubitCircuit
qc = QubitCircuit(1, num_cbits=1, reverse_states=False)
qc.add_gate("X", targets=0, classical_controls=[0])
print(qc.latex_code())
qc.png
```
```
\documentclass[border=3pt]{standalone}
\usepackage[braket]{qcircuit}
\begin{document}
\Qcircuit @C=1cm @R=1cm {
&  &  \gate{X}  & \qw \\ 
&  &  \ctrl{-1}  & \qw \\ 
}
\end{document}
```
A more complex test case:
```python
from qutip_qip.circuit import QubitCircuit, CircuitSimulator
from qutip_qip.operations import hadamard_transform
qc = …
```
=> fix circuit plot error for gates with classical controls when reverse_states=False

.readthedocs.yaml, doc/requirements.txt
By default, RTD does not execute the python files under `doc/source`. This update explicitly executes the python file.
Fix #219
=> Update the RTD configuration file to execute create_tutorials_html.py

.github/workflows/black.yml, .github/workflows/test.yml, src/qutip_qip/algorithms/qft.py, src/qutip_qip/circuit/__init__.py, src/qutip_qip/circuit/_decompose.py, src/qutip_qip/circuit/circuit.py, src/qutip_qip/compat.py, src/qutip_qip/compiler/__init__.py, src/qutip_qip/decompose/__init__.py, src/qutip_qip/device/__init__.py, src/qutip_qip/noise.py, src/qutip_qip/operations/__init__.py, src/qutip_qip/pulse.py, src/qutip_qip/qasm.py, src/qutip_qip/qir.py, src/qutip_qip/qiskit/backend.py, src/qutip_qip/qiskit/converter.py, src/qutip_qip/qubits.py, src/qutip_qip/vqa.py, tests/test_compiler.py
Update the black version to 24 and fix bugs in scipy `1.12`
=> Update black version and fix it to version to 24

src/qutip_qip/qasm.py, tests/test_circuit.py, tests/test_device.py, tests/test_optpulseprocessor.py, tests/test_scheduler.py
`QubitCircuit.compute_unitary()` is faster after the refactoring and saves memory.
=> Remove the unnecessary use of circuit.propagatos

.github/workflows/build.yml, .github/workflows/build_documentation.yml, .github/workflows/test.yml, README.md, doc/source/conf.py, doc/source/contribution-code.rst, doc/source/installation.rst, doc/source/tutorials-website/tutorials.html.jinja, setup.cfg
The minimum supported Python version is now 3.9
=> Drop support of Python=3.7 and 3.8

src/qutip_qip/operations/gates.py, tests/test_gates.py
Transform the qobj to CSR only if it is Dense, in case more data types are introduced in the future.
=> Use CSR as default for expand_operator

doc/source/w-state.qasm, src/qutip_qip/qasm.py, tests/qasm_files/bracket_error.qasm, tests/qasm_files/command_error.qasm, tests/qasm_files/qasm_error.qasm, tests/qasm_files/qft.qasm, tests/qasm_files/teleportation.qasm, tests/qasm_files/test_add.qasm, tests/qasm_files/test_custom_gates.qasm, tests/qasm_files/w-state.qasm, tests/qasm_files/w-state_with_comments.qasm, tests/test_qasm.py
Remove the ambiguous mode "qiskit" and add "default", "predefine_only" and "external_only".
Fix #208
=> Update the parsing mode for read_qasm

.github/workflows/black.yml, .github/workflows/build.yml, .github/workflows/build_documentation.yml, .github/workflows/test.yml
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> Update github actions version

doc/source/qip-simulator.rst, src/qutip_qip/circuit/circuit.py, src/qutip_qip/circuit/circuitsimulator.py, tests/test_circuit.py
Refactor the gate level `CircuitSimulator`
- Avoid expanding all propagators and then applying them one by one. Only expand when applying the unitary. This saves memory and also make it easier for further improvement, i.e., exploring other ways to perform the matrix multiplication (e.g. `einsum`).
- Switch some public members to private. Those members that track the execution of the circuit evaluation should not be public.
- Small changes to improve the clarity.
=> Simplify the structure of `CircuitSimulator`

src/qutip_qip/circuit/circuit.py
@gadhvirushiraj 
In your example in #253 you defined `start` but not `end`, that is a bit weird way of using it. I think it is better to use `qubits=` in that case. I write now an explicit error message.
Would you like to review the changes I made?
=> Fix a bug in add_1q_gate

doc/source/qip-basics.rst, src/qutip_qip/circuit/base_renderer.py, src/qutip_qip/circuit/mat_renderer.py
- Single-qubit circuit plotting faced dimensional inconsistencies, particularly with figure aspect ratios when title is added. Also, particular case of Single Qubit Circuit the visible plot size in IPython is not visible. 
- Unable to plot globalphase gate
- Separate plotting dimensions specifically for IPython environments
- Adjusted figure sizing to be dynamic, removing direct user control over figure size to maintain aspect ratio.
=> Fix Plotting Dimensions and Aspect Ratio Consistency

tests/test_renderer.py
Fixes #249
Added a test to verify that the Matplotlib, Text, and LaTeX renderers  saves circuit files in `PNG, TXT, and PDF` formats. The test checks file creation using the `tmpdir` fixture for multiple QC fixtures.
=> Added file save checks for renderers

src/qutip_qip/operations/gates.py
Recent changes in qutip give priority to sparse format in `tensor`, breaking a test:
`tensor( CSR, Dense) -> CSR`
This ensure the output of `expand_operator` is the expected dtype.
=> Ensure `expand_operator` output dtype

src/qutip_qip/algorithms/__init__.py, src/qutip_qip/algorithms/qft.py, src/qutip_qip/algorithms/qpe.py, src/qutip_qip/operations/gateclass.py, tests/test_qpe.py
Adding quantum phase estimation in the list of algorithms. Issue #264
=> Add quantum phase estimation in the list of algorithms
