qutip/qutip-qip

src/qutip_qip/circuit.py, src/qutip_qip/circuit_latex.py
Same as https://github.com/qutip/qutip/pull/1447
=> Fix circuit latex plot

src/qutip_qip/device/processor.py
Same as https://github.com/qutip/qutip/pull/1446
=> Improve plotting and add pulse_mode

src/qutip_qip/device/processor.py, src/qutip_qip/noise.py, src/qutip_qip/pulse.py, tests/test_noise.py
Same as https://github.com/qutip/qutip/pull/1445
=> Improve the noise module

src/qutip_qip/compiler/cavityqedcompiler.py, src/qutip_qip/compiler/gatecompiler.py, src/qutip_qip/compiler/instruction.py, src/qutip_qip/compiler/scheduler.py, src/qutip_qip/compiler/spinchaincompiler.py, src/qutip_qip/device/cavityqed.py, src/qutip_qip/device/modelprocessor.py, src/qutip_qip/device/optpulseprocessor.py, src/qutip_qip/device/processor.py, src/qutip_qip/device/spinchain.py, src/qutip_qip/noise.py, src/qutip_qip/pulse.py, src/qutip_qip/scheduler.py, tests/test_compiler.py, tests/test_device.py, tests/test_processor.py, tests/test_scheduler.py
Same to https://github.com/qutip/qutip/pull/1444
=> Integrate scheduler into the compiler

src/qutip_qip/circuit.py, tests/test_qubitcircuit.py
* Fixed bugs in _gate_FREDKIN function
* Added test
Same as https://github.com/qutip/qutip/pull/1489
=> Fixed bugs in _gate_FREDKIN function 

src/qutip_qip/device/circuitqed.py
ZZ cross talk was wrongly commented.
The initial value of anharmonicity was set wrong.
=> Fix bugs in circuitqed

docs/source/conf.py
The doc version was wrongly set to 0.0.1
=> Fix the doc version.

README.md, docs/source/installation.rst, requirements.txt, setup.cfg, src/qutip_qip/device/cavityqed.py, src/qutip_qip/device/circuitqed.py
This is the first release so there is not much change or cherry-pick needed. Only the development status.
=> Prepare the v0.1.0 release

README.md
document upgrade pip in readme as many folks on miniconda may experience the issue, I think.
=> upgrade pip in readme

.github/workflows/test.yml
There was a syntax error in the test workflow added in https://github.com/qutip/qutip-qip/pull/31, fix it.
=> Correct the test workflow

doc/source/installation.rst
=> Broken link in the installation guide

src/qutip_qip/circuit.py, tests/test_processor.py
Migrated from the qutip main repo, see commit info.
=> Minor bug fix and docstring improvement from qutip.qip

doc/source/qip-processor.rst
They were not caught because they are plotting code and plotting was not included in the doctest.
=> Minor fix for plots in doc

doc/pulse-paper/qft.py
Minor corrections on the labels and plotting settings. The manuscript is correct, I forgot to push this. Raise the PR just to make everything consistent.
=> Minor correction on the figure label and settings

setup.cfg, src/qutip_qip/circuit_latex.py
Fix the numpy version before the new qutip release.
=> Fix numpy version<=1.21 and black test

doc/source/qip-basics.rst
@BoxiLi I have updated my previous PR #131
=> Updated PR #131

doc/source/changelog.rst
=> Update changelog for the latest release

doc/source/qip-basics.rst, src/qutip_qip/circuit/circuitsimulator.py, src/qutip_qip/operations/gateclass.py, tests/test_circuit.py
The classical controlled values were not correctly passed to the simulator.
=> Fix a bug in the classical controlled gate

src/qutip_qip/circuit/circuit.py, tests/test_circuit.py
=> Add a minus sign for plotting the swap gate

setup.py
Copied from https://github.com/qutip/qutip/pull/2037
=> Fix parsing of package versions in packaging 22.

src/qutip_qip/circuit/circuit.py, src/qutip_qip/compiler/scheduler.py
=> Improve the docs for QubitCircuit.add_gate

.github/workflows/test.yml, doc/requirements.txt, setup.cfg, tests/pytest.ini, tests/test_qiskit.py
=> Update qiskit support version

.github/workflows/test.yml, src/qutip_qip/device/optpulseprocessor.py, tests/test_optpulseprocessor.py
Make the test based on `qutip.control` optional.
Restrict the test in one test case.
=> Use qutip_qtrl master branch and make tests optional

.gitignore, src/qutip_qip/circuit/__init__.py, src/qutip_qip/circuit/circuit.py, src/qutip_qip/circuit/color_theme.py, src/qutip_qip/circuit/mat_renderer.py, src/qutip_qip/operations/gateclass.py
=> matplotlib circuit rendering module

src/qutip_qip/circuit/circuit.py, tests/test_circuit.py
=> Fix a bug in add_1q_gates

src/qutip_qip/device/circuitqed.py, src/qutip_qip/noise.py
=> Use wq instead of wr for zz_coeff
